import { MobileLayout } from "@/components/MobileLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ChevronLeft, Download, CheckCircle, AlertTriangle, Loader2 } from "lucide-react";
import { Link, useRoute } from "wouter";
import { Badge } from "@/components/ui/badge";
import { useQuery } from "@tanstack/react-query";
import { fetchCase, type Case } from "@/lib/api";
import { useToast } from "@/hooks/use-toast";
import { format } from "date-fns";

type ExtendedCase = Case & {
  disposition?: string;
  dischargeSummary?: string;
};

export default function DispositionSummaryPage() {
  const [, params] = useRoute("/cases/:id/disposition");
  const id = params?.id || "";
  const { toast } = useToast();

  const { data: caseData, isLoading, error } = useQuery<ExtendedCase>({
    queryKey: ["case", id],
    queryFn: () => fetchCase(id) as Promise<ExtendedCase>,
    enabled: !!id,
  });

  const getDispositionLabel = (value: string) => {
    const labels: Record<string, string> = {
      'discharged': 'Discharged Home',
      'admitted': 'Admitted',
      'transferred': 'Transferred',
      'ama': 'Left AMA',
      'observation': 'Observation'
    };
    return labels[value] || value;
  };

  const getDispositionColor = (value: string) => {
    const colors: Record<string, string> = {
      'discharged': 'bg-green-100 text-green-700',
      'admitted': 'bg-blue-100 text-blue-700',
      'transferred': 'bg-purple-100 text-purple-700',
      'ama': 'bg-red-100 text-red-700',
      'observation': 'bg-amber-100 text-amber-700'
    };
    return colors[value] || 'bg-gray-100 text-gray-700';
  };

  const generateSummaryText = () => {
    if (!caseData) return "";
    
    const firstName = caseData.patientName.split(' ')[0];
    const caseIdentifier = caseData.mrn ? `${firstName} - ${caseData.mrn}` : firstName;
    
    let summary = `DISPOSITION SUMMARY\n`;
    summary += `${"=".repeat(50)}\n\n`;
    summary += `Case: ${caseIdentifier}\n`;
    summary += `Age: ${caseData.age} years | Gender: ${caseData.gender}\n`;
    summary += `Date: ${caseData.recordedAt ? format(new Date(caseData.recordedAt), "MMMM d, yyyy - HH:mm") : "N/A"}\n\n`;
    
    if (caseData.disposition) {
      summary += `DISPOSITION: ${getDispositionLabel(caseData.disposition)}\n\n`;
    }
    
    if (caseData.assessment) {
      summary += `FINAL NOTES:\n${"-".repeat(30)}\n${caseData.assessment}\n\n`;
    }
    
    if (caseData.differentialDiagnosis && caseData.differentialDiagnosis.length > 0) {
      summary += `DIAGNOSIS:\n${"-".repeat(30)}\n`;
      caseData.differentialDiagnosis.forEach((dx: any, i: number) => {
        summary += `${i + 1}. ${dx.diagnosis} (${dx.icdCode})\n`;
      });
      summary += "\n";
    }
    
    if (caseData.plan) {
      summary += `TREATMENT PLAN:\n${"-".repeat(30)}\n${caseData.plan}\n\n`;
    }
    
    if (caseData.dischargeMedications && caseData.dischargeMedications.length > 0) {
      summary += `MEDICATIONS:\n${"-".repeat(30)}\n`;
      caseData.dischargeMedications.forEach((med: any) => {
        summary += `- ${med.name} ${med.dose}, ${med.frequency} for ${med.duration}\n`;
        if (med.instructions) summary += `  (${med.instructions})\n`;
      });
      summary += "\n";
    }
    
    if (caseData.patientEducation) {
      summary += `PATIENT EDUCATION:\n${"-".repeat(30)}\n${caseData.patientEducation}\n\n`;
    }
    
    if (caseData.treatmentRedFlags) {
      summary += `WARNING SIGNS - RETURN IF:\n${"-".repeat(30)}\n${caseData.treatmentRedFlags}\n\n`;
    }
    
    summary += `FOLLOW-UP:\n${"-".repeat(30)}\nFollow up with your primary care physician within 3-5 days or sooner if symptoms worsen.\n\n`;
    
    summary += `${"=".repeat(50)}\n`;
    summary += `Generated by MedNote AI on ${format(new Date(), "MMMM d, yyyy - HH:mm")}\n`;
    
    return summary;
  };

  const handleDownload = () => {
    const summary = generateSummaryText();
    const blob = new Blob([summary], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const firstName = caseData?.patientName?.split(' ')[0] || "case";
    const mrn = caseData?.mrn || id.slice(0, 8);
    a.download = `disposition-${firstName}-${mrn}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({
      title: "Downloaded",
      description: "Disposition summary downloaded as text file.",
    });
  };

  if (isLoading) {
    return (
      <MobileLayout showNav={false}>
        <div className="flex items-center justify-center h-full">
          <div className="text-center">
            <Loader2 className="w-8 h-8 animate-spin mx-auto mb-4 text-primary" />
            <p className="text-muted-foreground">Loading disposition...</p>
          </div>
        </div>
      </MobileLayout>
    );
  }

  if (error || !caseData) {
    return (
      <MobileLayout showNav={false}>
        <div className="flex flex-col items-center justify-center h-full p-6">
          <AlertTriangle className="w-12 h-12 text-red-500 mb-4" />
          <h2 className="text-lg font-semibold mb-2">Case Not Found</h2>
          <p className="text-muted-foreground text-center mb-4">
            The case you're looking for doesn't exist or couldn't be loaded.
          </p>
          <Link href="/cases">
            <Button>Back to Cases</Button>
          </Link>
        </div>
      </MobileLayout>
    );
  }

  const firstName = caseData.patientName.split(' ')[0];
  const caseIdentifier = caseData.mrn ? `${firstName} - ${caseData.mrn}` : firstName;

  return (
    <MobileLayout showNav={false}>
      <header className="px-4 py-4 flex items-center justify-between sticky top-0 bg-background/80 backdrop-blur-md z-10 border-b border-slate-100 dark:border-slate-800">
        <Link href={`/cases/${id}`} className="p-2 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full transition-colors" data-testid="button-back">
          <ChevronLeft className="w-5 h-5 text-foreground" />
        </Link>
        <span className="font-semibold text-sm">Disposition Summary</span>
        <Button variant="ghost" size="icon" className="h-9 w-9" onClick={handleDownload} data-testid="button-download">
          <Download className="w-4 h-4" />
        </Button>
      </header>

      <div className="p-6 pb-24">
        <Card className="border-none shadow-lg bg-white dark:bg-slate-900 mb-6 overflow-hidden">
          <div className="h-2 bg-gradient-to-r from-indigo-500 to-blue-600" />
          <CardHeader className="pb-2">
            <div className="flex items-center justify-between">
              <CardTitle className="text-lg">Case: {caseIdentifier}</CardTitle>
              {caseData.disposition && (
                <Badge className={getDispositionColor(caseData.disposition)}>
                  {getDispositionLabel(caseData.disposition)}
                </Badge>
              )}
            </div>
            <p className="text-sm text-muted-foreground">
              {caseData.age} yrs | {caseData.gender} | {caseData.recordedAt ? format(new Date(caseData.recordedAt), "MMM d, yyyy") : ""}
            </p>
          </CardHeader>
          <CardContent className="space-y-6">
            {caseData.assessment && (
              <div>
                <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Final Notes</h3>
                <p className="text-sm text-foreground bg-slate-50 dark:bg-slate-800/50 rounded-lg p-3">
                  {caseData.assessment}
                </p>
              </div>
            )}

            {caseData.differentialDiagnosis && caseData.differentialDiagnosis.length > 0 && (
              <div>
                <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Diagnosis</h3>
                <div className="space-y-2">
                  {caseData.differentialDiagnosis.map((dx: any, idx: number) => (
                    <div key={idx} className={`flex items-center justify-between p-2 rounded-lg ${idx === 0 ? 'bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800' : 'bg-slate-50 dark:bg-slate-800/50'}`}>
                      <span className="text-sm font-medium">{idx + 1}. {dx.diagnosis}</span>
                      <span className="text-xs text-muted-foreground font-mono">{dx.icdCode}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {caseData.plan && (
              <div>
                <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Treatment Plan</h3>
                <p className="text-sm text-foreground bg-slate-50 dark:bg-slate-800/50 rounded-lg p-3 whitespace-pre-wrap">
                  {caseData.plan}
                </p>
              </div>
            )}

            {caseData.dischargeMedications && caseData.dischargeMedications.length > 0 && (
              <div>
                <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Medications</h3>
                <div className="space-y-2">
                  {caseData.dischargeMedications.map((med: any, idx: number) => (
                    <div key={idx} className="bg-violet-50 dark:bg-violet-900/20 border border-violet-200 dark:border-violet-800 rounded-lg p-3">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="font-semibold text-sm">{med.name}</span>
                        <Badge variant="outline" className="text-xs font-mono">{med.dose}</Badge>
                      </div>
                      <p className="text-xs text-muted-foreground">{med.frequency} for {med.duration}</p>
                      {med.instructions && (
                        <p className="text-xs text-violet-700 dark:text-violet-400 mt-1 italic">{med.instructions}</p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {caseData.patientEducation && (
              <div>
                <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Patient Education</h3>
                <p className="text-sm text-foreground bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800 rounded-lg p-3">
                  {caseData.patientEducation}
                </p>
              </div>
            )}

            {caseData.treatmentRedFlags && (
              <div>
                <h3 className="text-xs font-bold text-red-500 uppercase tracking-wider mb-2 flex items-center gap-2">
                  <AlertTriangle className="w-3 h-3" />
                  Warning Signs
                </h3>
                <p className="text-sm text-foreground bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-3">
                  {caseData.treatmentRedFlags}
                </p>
              </div>
            )}

            <div>
              <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Follow-up</h3>
              <p className="text-sm text-foreground bg-slate-50 dark:bg-slate-800/50 rounded-lg p-3">
                Follow up with your primary care physician within 3-5 days or sooner if symptoms worsen.
              </p>
            </div>
          </CardContent>
        </Card>

        <Button 
          onClick={handleDownload} 
          className="w-full bg-gradient-to-r from-indigo-500 to-blue-600 hover:from-indigo-600 hover:to-blue-700 text-white shadow-lg"
          data-testid="button-download-summary"
        >
          <Download className="w-4 h-4 mr-2" />
          Download Summary as Text File
        </Button>
      </div>
    </MobileLayout>
  );
}
